server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql:///gamecardsale
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
  thymeleaf:
    ncoding: utf-8
    cache: false
    mode: LEGACYHTML5
mybatis:
  type-aliases-package: org.java.entity
  mapper-locations: mapper/*Mapper.xml
